# -*- coding: utf-8 -*-
"""chat_with_data_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DxX_e2qcAM4wLVWkf4hE6T-M8ZUu8t1p
"""

# pip install needed libraries

pip install langchain

pip install langchain_experimental

pip install openai

# import needed libraries
import os
import pandas as pd
from langchain.llms import OpenAI
from langchain_experimental.agents.agent_toolkits import create_csv_agent

# load global parameters
def load_parameters():
    global temperature, max_iterations
    # Load parameters from configuration file, environment variables, or any other source
    temperature = 0  # Example value, replace with actual loading logic
    max_iterations = 30  # Example value, replace with actual loading logic

# setup open ai access in environment
def setup_openai_environment():
    # Set OpenAI API key
    os.environ["OPENAI_API_KEY"] = ""  # Replace with actual OpenAI API key

# create core csv agent which is based on the input query, iteratively create python script and run it
def create_agent(csv_filepath):
    # Create an agent using the CSV file
    return create_csv_agent(OpenAI(temperature=temperature),
                            csv_filepath,
                            verbose=False,
                            max_iterations=max_iterations)

# create main function, which will call all the previously build components sequentially
def main():
    # Load parameters
    load_parameters()

    # Load CSV file
    csv_filepath = "FM_v9.csv"

    # Set up OpenAI environment
    setup_openai_environment()

    # Create agent
    agent = create_agent(csv_filepath)

    # Run the agent with a prompt
    results  = agent.run("print the name of non numeric column in the data set")

    print(results)

if __name__ == "__main__":
    main()

